---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: auth-service-api-keys
  namespace: uo-staging
spec:
  encryptedData:
    auth-service-key: AgBnYT+/cY1TkgMTv9j2wLxBIAde+b6lq9793/J0kYGwRiuje/81Nej2qZHpO39HirkM3z4+C+3jqooLFRzQf5aJjg4zHVdQ/l/AYsoyk0qTeRY+ZFJZefqo9RUwOpXSCFvg+9B24ggUJ5gu+QrBvjcjuXp67yb6rL4rlYoiwCloUYsigKEAXsIHPZi4tSPDBa8DD+sg50iRcQNXBtkJMJ81GIPCdz+YC21p07QDyqzudndGWpejZq5zZv+GCN0bHghxq2z609RH0YYKUfy/0zfzOLyx1qqYwFvochjeY3Jpihvw4AQfA4F+TXFyOs/FEZcxcVckJ72mCVX4rUVxuCQaHzA0DO82w08F7IsHyhF5ytIWIN0M7wQlWvAvsGEfjG8d7UpodDmfMPtzl2HA0iIORITk1MvkYXQw3H1h36rD0e5dFtFJbdJFL7JKHbnLl+gXcgRf6DqwHC5p/NNvFQK2TZRYOJhxIA/ZKHpvLDJtXzcKLs+XTgrXkcvtMinuxFLjHQ3Xt7M8XbGNDshuwxgpxsWcODt/FmTbvQuMCrMrm5/u1RCNH3uWzx98aE4vdhr4C+46nlbt1Il0MX9KYh+1Qu2cKEKsr6putwY+cy/o9127fDNLSN1h/1WsO+xf+MdnzBTlNtYTtlUdPVt7wADBBP3OSLs+NWl0td4siCGd6nIC1+1JQElyDtdkUif9LTXvSX1iHVTqiOHQjn8htXp4y3LVSxdfzmc6+TM/mf/9EhoYqkGq6zJ8+lztfObPGnsMc3Jk1QS1dj6ZAe5bvCOt
  template:
    metadata:
      creationTimestamp: null
      name: auth-service-api-keys
      namespace: uo-staging
