apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  description: Dev environment workloads
  sourceRepos:
    - https://github.com/KominskyOrg/unifyops-infra
    - https://github.com/KominskyOrg/unifyops-infra.git
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
  # Allow all resource types in dev for flexibility
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'