apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
spec:
  description: Production environment workloads
  sourceRepos:
    - https://github.com/KominskyOrg/unifyops-infra
    - https://github.com/KominskyOrg/unifyops-infra.git
  destinations:
    - namespace: prod
      server: https://kubernetes.default.svc
  # More restrictive in production
  clusterResourceWhitelist:
    - group: ''
      kind: 'Namespace'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'