apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
  namespace: argocd
spec:
  description: Production environment
  destinations:
  - namespace: prod
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'