apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart: opentelemetry-collector
    targetRevision: ">=0.94.0"
    helm:
      valueFiles: ["values.yaml"]
  syncPolicy:
    automated: { prune: true, selfHeal: true }
