apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://github.com/prometheus-operator/prometheus-operator
    targetRevision: v0.77.1
    path: bundle.yaml
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["ServerSideApply=true"]
