fullnameOverride: kps

grafana:
  enabled: true
  ingress:        # We publish ingress separately in prom-addons to match your pattern
    enabled: false
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 5Gi

# alertmanager:
#   alertmanagerSpec:
#     retention: 120h
#     storage:
#       volumeClaimTemplate:
#         spec:
#           storageClassName: longhorn
#           accessModes: ["ReadWriteOnce"]
#           resources: { requests: { storage: 5Gi } }
#   config:
#     route:
#       receiver: devnull
#       group_by: ['alertname','cluster','namespace']
#       group_wait: 30s
#       group_interval: 5m
#       repeat_interval: 4h
#     receivers:
#       - name: devnull

prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources: { requests: { storage: 20Gi } }
    additionalScrapeConfigs:
      name: kps-additional-scrape-configs
      key: additional-scrape-configs.yaml

# k3s-friendly: disable components not exposed in k3s by default
kubeScheduler: { enabled: false }
kubeControllerManager: { enabled: false }
kubeProxy: { enabled: false }
