---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: externaldns-aws
  namespace: uo-infra
spec:
  encryptedData:
    aws_access_key_id: AgCJGavm51RL2ZdcfSTcVs90iAZHF6ZiRkejS/523EblRgkloAPt/1ZMsFkFfQLxWMuy+c0AMAbSk04mNIu8pFldDbDxYkxIkKiHrnsOejlsmVMZpCW9mS8vwPeU+23SnfFpbLKTHwf2e1omhF1aaYLMDl6dpVg8ca6KD6K7KQycyfuCn9axZjP7iZ1oN0vs4/JOtceI/kB3iu9AvkQOjKBPe1UYboldp1aLKHwfpB49AjKFMNd2/uptDvTuY6mYKuNxJyfVCIILGITwor+pp6gvWDyo5fd75zwINQu6XA1caBOrK6IrjRWXtT+Rvd/WRA1YA3eFhmZ7R+TCIicM9f5vy0dGhUf6Ws+ZTdv96O57AXsDub+noaGOlSVuz9J27AM9ccdskqPmQmi9LooSx2wBakny1wAPFZTmCrfM4OzS+N5yBmIyjuioJpUPOT9Lb1Kh1OD4P+ebZLsIA+12aLtF9DaL0Kw56ke5maRhIPXgIVUDA8j0Oy33mnWLGA9YiE+SKp97PcwZzCUbCqrTUKggoANDjJvlcQsUyi/KcnGqFCd8i8e8NcLsri7NxZifQ2dXNpCEK0L5WM+VmCqTQ6H2NXYtjaXY3jR7iRJu9O0B+SNBTAuxRpddT2orrUZKlk0VY0zqo4c3L+gAUO7I5bu6yqFMZzCeo/7fXMuCb5dvixuD0mrgcTiBCYYIs5QoNO2MliM9+9kd21VKjEGvZlf6dRPxqg==
    aws_secret_access_key: AgCfV9xbX10z62DAluYfGUsZ3HhUW8bjiytNBrfGsDkXfa4j++idrK4u9hQDQQ2y+MFuDe0PgJSL63gWqdSkmXxf0shZTGLjXfRkAwqsCzLSj9dCHhnL2gU8PWajNFmDAPijyF9flPqqMOPrsuC6KnGveJGqxV7ucyFy1nDm5ERFhAk+pmCA8Y8/9Q306CYhaK7xfr9TXzwzvBv/H4gMSfkztFVrORIRCPX/D7Up3CDbChH0UWgpTwSs72cT3ms9MVLUGOIp+FqGxIIXqXogxgP4lDHOAAfUgM99CNAwqtm7n32j8LQL5x00YX/gvoM0CKMW7ZebCrBRFHPaqiS6JThrF1WQTn+u7rq1UtqEegIlYC2lNJugr905cgWZR7YLk8S50QsrHDfp/czXdx2FfmTKV7wTRN9MfIqZ2ewnPpu34uU4PQjfgdOiimsLn1ogi5s8lRyVZjsaKJOzCn4zQ0mlhzlumoV5mCNm9cBTO91ZTy+C7AXTlGy1G+91my08R16+uCmlYRVjEic5BZ5HcKZ0e9DlCGXXhiClNNArBY0iayB9JPyvj/nvsmCDMY4UasKggmLIGHB0iLhSWtd+QDmNBhCJgDsGn+19idwfo/XwfIKE5YZ5Sz4hcniOhren4CxMKD4zKGb2wlh15iGyUyGs4cqD32+gmTVlVoixo7skhVJYJvaVaqGgOTM2O20onqNlbhw/f2S4bUaL2WtjdNTYgkBB0HX8vYbTeK0YlKjylVy4EV4qZcUP
  template:
    metadata:
      creationTimestamp: null
      name: externaldns-aws
      namespace: uo-infra
    type: Opaque
