# This creates a self-signed CA certificate that other certificates can use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
  namespace: cert-manager
spec:
  isCA: true
  commonName: unifyops-ca
  secretName: ca-key-pair
  duration: 87600h # 10 years
  renewBefore: 720h # 30 days
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.local"
    - "*.unifyops.local"