apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alloy-agent
  namespace: observability
  labels:
    app: alloy
    release: kps
spec:
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
  namespaceSelector:
    matchNames:
    - observability
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alloy-gateway
  namespace: observability
  labels:
    app: alloy
    release: kps
spec:
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
      app.kubernetes.io/instance: alloy-gateway
  namespaceSelector:
    matchNames:
    - observability