apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki
  namespace: observability
  labels:
    app: loki
    release: kps
spec:
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: loki
  namespaceSelector:
    matchNames:
    - observability