apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metrics-server
  namespace: observability
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      k8s-app: metrics-server
  endpoints:
    - port: https
      scheme: https
      interval: 30s
      tlsConfig:
        insecureSkipVerify: true
      path: /metrics
