apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tempo
  namespace: observability
  labels:
    app: tempo
    release: kps
spec:
  endpoints:
  - port: tempo-prom-metrics
    path: /metrics
    interval: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
  namespaceSelector:
    matchNames:
    - observability