apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
spec:
  project: arc
  source:
    repoURL: oci://ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: "0.12.1"
    helm:
      oci: true
      passCredentials: true
      values: |
        githubConfigUrl: "https://github.com/KominskyOrg"
        githubConfigSecret: "github-token"
        minRunners: 0
        maxRunners: 5
        controllerServiceAccount:
          namespace: arc-systems
          name: gha-runner-scale-set-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: github-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
