apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-controller
  namespace: argocd
spec:
  project: arc
  source:
    chart: gha-runner-scale-set-controller
    repoURL: oci://ghcr.io/actions/actions-runner-controller-charts
    targetRevision: "0.9.3"
    helm:
      oci: true
      passCredentials: true
      values: |
        serviceAccount:
          create: true
          name: gha-runner-scale-set-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-systems
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
