apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  project: arc
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: "0.13.0"
    helm:
      values: |
        githubConfigUrl: "https://github.com/KominskyOrg"
        githubConfigSecret: "github-token"
        minRunners: 1
        maxRunners: 5
        controllerServiceAccount:
          namespace: arc-systems
          name: gha-runner-scale-set-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: github-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
