apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  project: arc
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    chart: gha-runner-scale-set
    targetRevision: "0.13.0"
    helm:
      values: |
        githubConfigUrl: "https://github.com/KominskyOrg"
        githubConfigSecret: "github-token"
        minRunners: 0
        maxRunners: 5
        controllerServiceAccount:
          namespace: arc-systems
          name: gha-runner-scale-set-controller
        containerMode:
          type: "dind"
        template:
          spec:
            initContainers:
            - name: init-dind-externals
              image: ghcr.io/actions/actions-runner:latest
              command: ["cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/"]
              volumeMounts:
              - name: dind-externals
                mountPath: /home/runner/tmpDir
            containers:
            - name: runner
              image: ghcr.io/actions/actions-runner:latest
              command: ["/home/runner/run.sh"]
              env:
              - name: DOCKER_HOST
                value: tcp://localhost:2376
              - name: DOCKER_TLS_VERIFY
                value: "1"
              - name: DOCKER_CERT_PATH
                value: /certs/client
              volumeMounts:
              - name: work
                mountPath: /home/runner/_work
              - name: dind-sock
                mountPath: /var/run
              - name: dind-externals
                mountPath: /home/runner/externals
              - name: dind-cert
                mountPath: /certs/client
                readOnly: true
            - name: dind
              image: docker:dind
              args:
              - dockerd
              - --host=unix:///var/run/docker.sock
              - --host=tcp://0.0.0.0:2376
              - --tlsverify
              - --tlscacert=/certs/server/ca.pem
              - --tlscert=/certs/server/cert.pem
              - --tlskey=/certs/server/key.pem
              env:
              - name: DOCKER_TLS_CERTDIR
                value: /certs
              securityContext:
                privileged: true
              volumeMounts:
              - name: work
                mountPath: /home/runner/_work
              - name: dind-sock
                mountPath: /var/run
              - name: dind-cert
                mountPath: /certs/client
              - name: dind-cert-server
                mountPath: /certs/server
            volumes:
            - name: work
              emptyDir: {}
            - name: dind-sock
              emptyDir: {}
            - name: dind-externals
              emptyDir: {}
            - name: dind-cert
              emptyDir: {}
            - name: dind-cert-server
              emptyDir: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: github-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
