apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-runner
spec:
  replicas: 1  # Can scale up for parallel jobs
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      serviceAccountName: github-runner
      containers:
      - name: runner
        image: summerwind/actions-runner:latest
        env:
        - name: RUNNER_SCOPE
          value: "org"  # or "repo" for repository-specific
        - name: GITHUB_OWNER
          value: "KominskyOrg"  # Your GitHub org
        - name: GITHUB_REPOSITORY
          value: ""  # Leave empty for org-wide, or specify repo
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-secret
              key: runner-token
        - name: RUNNER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUNNER_WORKDIR
          value: "/runner/_work"
        - name: DISABLE_RUNNER_UPDATE
          value: "true"
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: work
          mountPath: /runner/_work
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 2000m
            memory: 2Gi
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: work
        emptyDir: {}