apiVersion: v1
kind: Namespace
metadata:
  name: notes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trilium-data-pvc
  namespace: notes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn