# Longhorn Helm Chart Values
defaultSettings:
  # IMPORTANT: This path should match your NVMe mount point
  # Your 3.6TB NVMe (/dev/nvme0n1p1) should be mounted here
  defaultDataPath: /var/lib/longhorn
  
  # Replica count (for single node, set to 1)
  defaultReplicaCount: 1
  
  # Storage over-provisioning percentage
  storageOverProvisioningPercentage: 100
  
  # Storage minimal available percentage
  storageMinimalAvailablePercentage: 10

persistence:
  # Default StorageClass settings
  defaultClass: true
  defaultClassReplicaCount: 1
  reclaimPolicy: Delete

# Resource limits for Longhorn components (optional)
resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi