# clusters/unifyops-home/apps/observability/loki/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.21.1"
    helm:
      values: |
        deploymentMode: SingleBinary
        
        loki:
          auth_enabled: false
          
          # Empty commonConfig to override defaults
          commonConfig: {}
          
          storage:
            type: filesystem
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: admin
              
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          
          # Add storage_config for filesystem
          storageConfig:
            filesystem:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules
        
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 20Gi
            storageClass: longhorn
        
        # Ensure microservices components are disabled
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0
        
        gateway:
          enabled: false
        resultsCache:
          enabled: false
        chunksCache:
          enabled: false
        test:
          enabled: false
