# clusters/unifyops-home/apps/observability/loki/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "5.47.2"
    helm:
      values: |
        # Single binary deployment
        deploymentMode: SingleBinary
        
        loki:
          auth_enabled: false
          
          commonConfig:
            replication_factor: 1
            
          storage:
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: admin
              
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: boltdb-shipper
                object_store: filesystem
                schema: v12
                index:
                  prefix: loki_index_
                  period: 24h
        
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 20Gi
            storageClass: longhorn
        
        # Explicitly disable all distributed components
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        
        # Disable simple scalable components completely
        ingester:
          replicas: 0
        distributor:
          replicas: 0
        querier:
          replicas: 0
        queryFrontend:
          replicas: 0
        compactor:
          replicas: 0
        indexGateway:
          replicas: 0
        ruler:
          replicas: 0
        
        gateway:
          enabled: false
          replicas: 0
        
        test:
          enabled: false
