# clusters/unifyops-home/apps/observability/loki/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: ">=6.0.0"
    helm:
      values: |
        deploymentMode: SingleBinary
        read: { enabled: false }
        write: { enabled: false }
        backend: { enabled: false }
        gateway: { enabled: false }
        resultsCache: { enabled: false }
        chunksCache: { enabled: false }

        loki:
          auth_enabled: false
          server:
            http_listen_port: 3100
          
          # Explicitly disable commonConfig to avoid storage bucket issues
          commonConfig: false
          
          # Define storage type and bucket names (required for newer chart versions)
          storage:
            type: filesystem
            filesystem:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules
            bucketNames:
              chunks: filesystem
              ruler: filesystem
              admin: filesystem
          
          storage_config:
            filesystem:
              directory: /var/loki/chunks
            boltdb_shipper:
              active_index_directory: /var/loki/index
              cache_location: /var/loki/index_cache
              shared_store: filesystem
          
          schema_config:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h

        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 20Gi
            storageClass: longhorn

        service:
          ports:
            http: 3100
