# clusters/unifyops-home/apps/observability/loki/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "5.47.2"
    helm:
      values: |
        loki:
          auth_enabled: false
          
          commonConfig:
            replication_factor: 1
            path_prefix: /var/loki
            
          storage:
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: admin
              
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: boltdb-shipper
                object_store: filesystem
                schema: v12
                index:
                  prefix: loki_index_
                  period: 24h
        
        # Use the single binary deployment
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 20Gi
            storageClass: longhorn
        
        # Disable test pod
        test:
          enabled: false
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true", "ServerSideApply=true"]