apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "5.47.2"
    helm:
      skipCrds: true
      values: |
        deploymentMode: SingleBinary

        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
            path_prefix: /var/loki
          storage:
            bucketNames:
              chunks: chunks
              ruler: ruler
              admin: admin
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: boltdb-shipper
                object_store: filesystem
                schema: v12
                index:
                  prefix: loki_index_
                  period: 24h
          limits_config:
            retention_period: 168h  # 7d
          compactor:
            working_directory: /var/loki/compactor
            retention_enabled: true
          ruler:
            storage:
              type: local
              local:
                directory: /var/loki/rules

        singleBinary:
          enabled: true
          replicas: 1
          persistence:
            enabled: true
            size: 40Gi
            storageClass: longhorn

        # turn off agent/operator CRs completely
        monitoring:
          selfMonitoring:
            enabled: false
          grafanaAgent:
            enabled: false
            installOperator: false

        # disable helm test pod
        test:
          enabled: false
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: ["CreateNamespace=true", "ServerSideApply=true"]
