# Force single-process Loki (no object store)
deploymentMode: SingleBinary

# Disable all distributed components explicitly (belt + suspenders)
read:
  enabled: false
write:
  enabled: false
backend:
  enabled: false
gateway:
  enabled: false
resultsCache:
  enabled: false
chunksCache:
  enabled: false

# Loki core settings
loki:
  auth_enabled: false
  server:
    http_listen_port: 3100

  # Define storage type and bucket names (required for newer chart versions)
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin

  # --- STORAGE: local filesystem (PVC) ---
  # TSDB/boltdb-shipper on local disk
  storage_config:
    filesystem:
      directory: /var/loki/chunks
    boltdb_shipper:
      active_index_directory: /var/loki/index
      cache_location: /var/loki/index_cache
      shared_store: filesystem

  # Schema for TSDB (works fine for homelab)
  schema_config:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

# SingleBinary pod + PVC
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 20Gi
    storageClass: longhorn

# Service named "loki" on port 3100
service:
  ports:
    http: 3100

# turn OFF grafana-agent/operator CRD things
monitoring:
  selfMonitoring:
    enabled: false
    grafanaAgent:
      enabled: false
  dashboards:
    enabled: false
  rules:
    enabled: false

  # keep a ServiceMonitor so kube-prometheus-stack scrapes Loki /metrics
  serviceMonitor:
    enabled: true
    # If your Prometheus requires a label match, uncomment and set it here:
    # labels:
    #   release: kps
