loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
persistence:
  enabled: true
  storageClass: longhorn
  size: 20Gi
compactor:
  persistentVolume:
    enabled: true
    size: 5Gi
    storageClass: longhorn
