# clusters/unifyops-home/apps/observability/loki/values.yaml

# Deploy Loki as one single process (no object storage required)
deploymentMode: SingleBinary

loki:
  auth_enabled: false
  server:
    http_listen_port: 3100
  commonConfig:
    replication_factor: 1
  # Use local filesystem (backed by a PVC) instead of S3/GCS
  storage:
    type: filesystem
  limits_config:
    reject_old_samples: true
    reject_old_samples_max_age: 168h  # 7d
  # (Optional) keep defaults for schema, etc.

# PVC for the single-binary pod
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 20Gi
    storageClass: longhorn   # or storageClassName: longhorn

# Service is named "loki" on port 3100 by default
service:
  ports:
    http: 3100
