# clusters/unifyops-home/apps/observability/grafana-crds/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://github.com/KominskyOrg/unifyops-infra
    targetRevision: main
    path: clusters/unifyops-home/apps/observability/grafana-crds
    kustomize: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
