apiVersion: monitoring.grafana.com/v1alpha1
kind: LogsInstance
metadata:
  name: cluster-logs
  namespace: observability
spec:
  clients:
    - url: http://loki-gateway.observability.svc.cluster.local/loki/api/v1/push
  positions:
    filename: /var/lib/grafana-agent-positions/positions.yaml
    
---
apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  name: all-pods
  namespace: observability
spec:
  # recent operator versions use lokiName; older ones use instance
  # try this first:
  lokiName: cluster-logs
  # if your operator errors on lokiName, delete it and use:
  # instance: cluster-logs

  pipelineStages:
    - cri: {}
  target:
    namespaceSelector: {}
    selector: {}  # all pods; you can tighten later
