apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets-management
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: "dev"
            branch: "dev"
            namespace: "uo-dev"
            syncPolicy: "auto"
          - env: "staging"
            branch: "staging"
            namespace: "uo-staging"
            syncPolicy: "auto"
          # Production secrets are NOT managed by ArgoCD
          # They must be created manually in the cluster
  template:
    metadata:
      name: '{{env}}-secrets'
      labels:
        purpose: secrets-management
        environment: '{{env}}'
    spec:
      project: apps
      source:
        repoURL: https://github.com/KominskyOrg/unifyops-infra
        targetRevision: '{{branch}}'
        path: 'clusters/unifyops-home/secrets/{{env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: false  # Don't auto-delete secrets
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
