apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-ingress
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/KominskyOrg/unifyops-infra.git
    targetRevision: main
    path: apps/longhorn
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true