apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.7.2
    helm:
      values: |
        defaultSettings:
          defaultReplicaCount: 1
          createDefaultDiskLabeledNodes: false
          defaultDataPath: /var/lib/longhorn
        persistence:
          defaultClass: true
          defaultFsType: ext4
      # (keep skipCrds: false so Argo manages CRDs)
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /metadata/annotations
        - /spec/conversion/webhook/clientConfig/caBundle
        - /spec/versions
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
