apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-prod
  namespace: argocd
spec:
  project: app
  source:
    repoURL: https://github.com/KominskyOrg/unifyops-infra.git
    targetRevision: main
    path: envs/app
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions: [CreateNamespace=true]