apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projects
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/KominskyOrg/unifyops-infra.git
    targetRevision: main
    path: clusters/unifyops-home/projects
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true