# Auth App - Development Environment Overrides

image:
  tag: dev-latest
  pullPolicy: Always

ingress:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "dev.unifyops.io"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/gzip: "true"
    nginx.ingress.kubernetes.io/gzip-types: "text/css text/javascript application/javascript application/json"
  hosts:
    - host: dev.unifyops.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: dev-unifyops-tls
      hosts:
        - dev.unifyops.io

config:
  apiUrl: "https://dev.unifyops.io/api"
  authAppUrl: "https://dev.unifyops.io"
  appName: "UnifyOps Auth (Dev)"
  environment: "development"

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi