---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-status-token
  namespace: uo-dev
spec:
  encryptedData:
    token: AgCyckLIIHTAxZEyvZC06UMFmEL8RDG8lYh4VGOLpqnWLj2Go6jpKWD5uSYxzIG/Ah/n6xu3Nc6A5PC+if+4B3vE5Qx7eVuNtDRMmmMiXB7vcoYriYTEPGa82Hk7rlxLBDb9NQHHdVKZnp8gDne4IoLSR/x/uCnWhKT+WiFj1/FnYUqokiQ9U9g71Ny0WAiM+MAS4mJA68wSOVhOpa8FHqKAOLJOb6Q6NJJXOnPKkTP0ES/OsHlsq5MxU/sSj65bC2QZn8aEdGk0gADlEZk3/Osj4MFRpoDk5tF5n1+0urQWp+27eOMzgutydRUKJBoiEOP0N9OhzQtNJCHhB1lAlc54QxiRKTys0LyF9bE3IwsnacICDNMXcOmCk4K6K5RAEw7UnM9S7d6BdVE8e9/iNhfJvPnTl7bJLPGIB8dAMlhXmhflW3RgMWwhAvrOetX6VDUby/I2Ukd9hb5wIHCcZLRr2aRM8Ny9xUvDqtZNSBgS0eCRCjRmke86z0NjIRiIPrC2w86IYdCcl6qMqOylJ/Q4bZHdiK2Fu5nYCWvYMwOq4eNwvLJp//W9WS+qucE9JDrfdIq+GsT00n86lj+dJqi8UJ7DF0dMvQaqa6JeMLtT2/GztmCPs0RYSn38Jjy/YtJFZQ7TV18NARUSusAEAn7XKh3q5SjjFxM4+mtYOQEfagjUFA1tjkzBRWtBZ5SSvJJPtesgj8XKjago3p6b016TVQ++vULv4MkHCCyP82+mGe5iuItRByGghZ4xzyLkepzRUl2lujaItVotzzPdKBy1oO4kXQhR9SDLQutlKizBrIOidgxV3ecyxVZo9pUX3b0QfYUXXXyE/90aFTgXZc/CgQxwkd3qf/H14BDAtUpgHtbY1cuqGb2b9xtfTSIhtCNII8R6J1dAlL6plRTXUSdsuiJH3fQThL/296+lg1GffWWMV9uHi0yWYjayUNIybg3jzrYKoGTpyZaGQ1veApwGohBPXaqOpbH8icqbJj5QYvdSwURDZ+6KwGHifELO5V7HauzmteVQRtQwbw==
  template:
    metadata:
      creationTimestamp: null
      name: argo-status-token
      namespace: uo-dev
