---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-writer-token
  namespace: uo-dev
spec:
  encryptedData:
    token: AgCGyPpWNofEvUzRH4dfgCzY5v8o/UMQiMCb7/cVYCbPt4JLRGiV3WcDkoQMR3MPaBJwaJjuxHNRXaO63TjwrdYIq4kgkQCltZwUpNapy/0XWVz/B68BoKJ6//hwi9NrCONSZFFIOQU6oh7NE/iGNHiDYkogv59r/t0T2gChJYC4e+FCJShzasla5VMaW55YRNZwDr/ftJXbX8RkUWVXbQr5rfE0F+e0SGrvtPkLXX7XvTfbIa9AqQigCzJI/wfQwme0XApOq6bXJKWX30gMS2gvjAReCUu1NWN28xLmoDYvXkwGL3u/VdW93PNOGcqyqdXr4S/qzd3UDIp878F6n2zkaA8MrPBxXYUI+C3VeKG3sJhQf23YVCrCzX5z9pp65hvoinsqHsWX1KC6rNlesEdVAPXF3QQ5N6svSQW0GWW3DkBb4Llin6KyaT2HBir2jeLE6w5WlZRqq/G2yaG0XnRD1i7EST+ANMbDCKZ9cNFArtC+x5EimCMbnMe3xiCWELZKgBXUDB+6AHyOAIcd0V9in7XXRAOwh46veJdZ1MDahubgAIhVlVvRBHhPb5N9jnFQmj0JGDXHYakoDdS+Ycxb48SIi/aqECLkiigX7p/hjhb/reED9fcgN/oFAiRFNVyMxke7U+wS/FIEtAJY2hGh090bI2R/rOLuueQuQM+z6O3FYPrtpXQHfZw7cbhOD7N60HlRSs91iimvl56Mva+M8SNDn+s58un7Cw9yF2AA4JXNTOefPUpH5SqhR0iA4E/HTwyFHbN0BlR+yocT2oC4Mt5NUpEOc/VHvjuw3LU9E9qijxudrDVGtMMTD9k=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-writer-token
      namespace: uo-dev
