---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unifyops-postgresql-secret
  namespace: uo-dev
spec:
  encryptedData:
    postgres-password: AgCh67U3SDQGSIKLNzVOz0GJR2zSGneQDoX7iv3+y+TMw/LlzF5om0uLIlWoZQoGeAdDcWIB79kcwqaACyIRY6o13qvqyVauz1K39iN56J8Lp9899xgw5N5O7vthaxGpT1/WHhpdeu1mQr38q077Tqgj5aIQH5Dj5YPeq4Fm4e7q3RSylrQtGuxIB2gjAUZZDH+HS2HqEhVJCKzx2iClh1hYtevU2QqLaUXjK4qmmrFxyPnPTJiX6h+rPKIKReTpcsWgUX7qll9eRI6MxdliLzOC/abEeZ1wRF1kwG0FxxC03Ze4aKYlRgVBMTMXfOZFkTjxWEi3z5yVdWqZXb81LrGI2cR/8SagxTwT0JdICDKxlJVckvFxnZeyfzLUU80HbOKI7E/4OJoHTSxfVwKzunlVSOCYQ302vBNJLrLSfqBBoYnCmEo0fVdbtm+W7dSB3+ECm48JtEzsbcOpx+hotwMmIICRNxdyWDnOCGPKBmWlm0+lfUp8VqD88UTH5ipvj2j43eUrNmhDEMAWPuv67QXNY3mCSb+aVHqYTEOX9EQqGmtybKMtGnQew9q3CcWRlCf5gBAr+7NJ+SbnEtR2uKrHYqfxQBtM5nGO4k/oXjsgWfqbgie6sp1fVjxAXmeolu/0o7z4I9JD4DNSSxrGoEBAFyDft5+WpFwGjPgSe8FfcWtzQscih8pTuQYNhDoII09QcykpCtVc1NZCoBED2Yt1RnZhFU9gggOVC8OEunZNqQ==
  template:
    metadata:
      creationTimestamp: null
      name: unifyops-postgresql-secret
      namespace: uo-dev
