---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: unifyops-postgresql-secret
  namespace: uo-dev
spec:
  encryptedData:
    postgres-password: AgChM/J5Ywtw5jJkRleQhWBy3weOeRX2sqxzz6nLzyvYoLc+MYAiAi0jcAQr4+i6UqWSUcYnZWLnRoy0rR6sqMeCTF3ihgZ7KZgO0MQ6YEdIa3d2D0T5Hxft6aEWk66M3s6802pfnbLFTa/hBlnsFDtztgXQZx0tySAuonZvH4N33o9p3js0Bh7E+4TD4H5IFOeSp8/rC4+6DvULaKPEmDQ4moWvTv8kwkaNnVkSOhxbLMHRV91/q8eXuSv0S2GNCT5N+Z8vF00OanxPnkNKqf1YOvdrnEVAjAAvYYojJVE3bISx9ZGO0RGDOKKjpIwwjNs5Idv130oDDcZB2aGH9kstu7hN180v7QLYswHsDk9vzazqalDGI56KRQtnaWc1HMeX6mmWrHjsgZXJ2JWCpoxnECHTWiPuMX3TZAeYLX8vxxzlK1nvOvrAitzbbo9Q05mAn5gsMAOaxds4VAeXOfZgdnH+vBiiDdbqJhBnrTtmWh5P5ejNwWNpjsY/swBi0JAAfc1MkoAABoUFWEvJsrZ56QwMrjot4aQlq80ffVxGwL5yfQd6om0UTRbmcHeqdxXPwYEUgd53yyvTcy57FBxhK9S3+a4bII3LSyzF4T6aAFdsd3vMbN2D0SGbblaxnJF52RsDxcFF8bRu4Y6Q61IViiy1JA/nygS5pKm0yJgwoErkI/Sav08CtRr3JLCzr0VRzEx5NPW0kPx8jE69mM5FyM+6NJuQDR5r2G0aYjG52jY=
  template:
    metadata:
      creationTimestamp: null
      name: unifyops-postgresql-secret
      namespace: uo-dev
