apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.15.1
    helm:
      values: |
        provider: aws
        policy: upsert-only
        registry: txt
        txtOwnerId: unifyops-home
        domainFilters:
          - unifyops.io
        env:
          - name: AWS_REGION
            value: us-east-1
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: externaldns-aws
                key: aws_access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: externaldns-aws
                key: aws_secret_access_key
  destination:
    server: https://kubernetes.default.svc
    namespace: uo-infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
