apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: jared@unifyops.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z06017623B29BVK96HE8T
          accessKeyIDSecretRef:
            name: route53-credentials
            key: aws_access_key_id
          secretAccessKeySecretRef:
            name: route53-credentials
            key: aws_secret_access_key
