apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: ">=8.0.0"
    helm:
      values: |
        serviceMonitor:
          enabled: true
        config:
          modules:
            http_2xx:
              prober: http
              timeout: 5s
              http:
                preferred_ip_protocol: "ip4"

  syncPolicy:
    automated: { prune: true, selfHeal: true }
