---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: route53-credentials
  namespace: cert-manager
spec:
  encryptedData:
    aws_access_key_id: AgBwwZ5ICOTLCoSXVgDICpyN6+fFwncrmMZbD00DC3wirb16cq4irz2Q/sOnZo39fAPJOXP6u0vLX7MogO5cCC0BkfS25ZLcekbYnPzmmWPUFBvxQR3GQodx/MNgMBOv317i7HXgP0dgVtkaoKC21FlUK9eG4uVnJDAtToDss1ukUloCZndBSE3BtPoAHGr0boCwi9XZf/a4CqvX6ttJVdlzlVdW1x2Kf+1faSPPO0tg18ncFJ8fH5gLw0e+tBO7IZaBsp0lD9zmFPi0KK5EpCNsqjLvez5ssPX44Dg0TjxWDFQUgoHsyyq1vly2EHMR5OvxM/X5RQMF0xI/SVVb8yS37HT2NVPIQXoyJ+hIUjoI4B8FeLTANWCNMfWqMxGX+RZMc8xdWLBXUSDfUTNEj0cBXe9hnR8RnFc6aPr0ite9dYoDu6smkOBy7wjdRDcoyz8HPuQWWbV22N+rsJvMnQwjpVGM2xtzqeRNGaC8MhjLD4x3nR6Sz75cwE5LBiKosGuDZuH64iZ2qRii0ZE+e8NJ2B1GKbN+uzOYDWEY1I1MZ9LFQMSbRn1eCeXetp/HPsCpcxFanIHbF2ACKBCPtwgjpJJczjULGd+53HkXiLR+cwyj5EtME82VVf9LmfG+GQm5C7oyx0KXfii7mXWtCPsxetqXZQGKfIsilsAhZHV36pbUOVkRpDpt9Cj0cKwe3/ZcS3l+cbBS52ynHMhUbmw4OoA5Bg==
    aws_secret_access_key: AgCyGjscdIESS08MzgDzMQ3qaym7yeipyd/NmKD10dfgxIzx4Rc8W14+bLjCOmSHpHGJV0vHN34fz5hxPqjeYeADiTMkzGYuN++Du+/YnXKRxPY588V+LTZOsyEmX3/ZR/5L1VThXmJvMH7wz/UXzwVT+HmPUzdUV17ZDUT7ZqLmEZ75vS4kJlbLIL2Lo8poH85kSitOrnr7f2QluwcYTVvjKel/XL/XvaW4FMVFA0/PLXsXwnXSra85HfW0KTQns6oXiOYVSGN0CIIR1/fam+V+C/zI3jQS2ws7JQCH42hB45KG73Bw2xTdIrT6x9Q0QkKE4eFvFx4+RS7Pajh9oO5tNzVTROQUkjw+5tQFhTICSda8BALxMG5YECVSnxRrl4yWs4M5zvG6ZX63tusX46scRAIpDOiKYOipxZaho87OPg93ghOiysl+mPQKLaluUFU+AqeCC0pfMlmv+k5zPSt9PBU4HoCK7Jrch0H0A9ZS/HhITtf7OcOdtGHm9ZR1D2MU4JAat+7g9GNtVo06KVzl5ftT/ZfO1l8YjxcdbZVP/IJuPkTGlOo7kPxhcAI2rpirBRBy2F69/LhUMx5JM6O+ON9LB8J5Uk0GM0uZ1xcSrEKs1Q5yRqzHM9BclP599IeZz9vxXX0KfEoKJuTgyEWIIEcZevrZJ2AmNG5jglOgZMubUbU+b5vkYY4kLvdvU4R717ZRm4v+SdRdxQWnBGBEBKtFyFYoi+K/Eje+JqoDUlrmgLsuOdtA
  template:
    metadata:
      creationTimestamp: null
      name: route53-credentials
      namespace: cert-manager
