apiVersion: v1
kind: LimitRange
metadata:
name: defaults
namespace: uo-dev
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "500m"
        memory: "512Mi"