apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: uo-dev
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
  namespace: uo-dev
spec:
  podSelector: {}
  ingress:
    - from:
      - podSelector: {}
  egress:
  - to:
    - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-ingress-controller
  namespace: uo-dev
spec:
  podSelector: {}
  ingress:
    - from:
      - namespaceSelector:
        matchLabels:
          kube-system: "true"
    - namespaceSelector:
        matchLabels:
          name: ingress