expose:
  type: ingress
  tls:
    enabled: true
    certSource: auto
  ingress:
    className: traefik
    hosts:
      core: harbor.local
      notary: notary.local
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

externalURL: https://harbor.local

# Initial admin password - CHANGE THIS IN PRODUCTION
harborAdminPassword: "Harbor12345!"

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: longhorn
      size: 200Gi
    chartmuseum:
      storageClass: longhorn
      size: 10Gi
    jobservice:
      storageClass: longhorn
      size: 20Gi
    database:
      storageClass: longhorn
      size: 20Gi
    redis:
      storageClass: longhorn
      size: 5Gi
    trivy:
      storageClass: longhorn
      size: 20Gi

trivy:
  enabled: true
  vulnType: "os,library"
  severity: "HIGH,CRITICAL"
  ignoreUnfixed: true
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 500m

# Enable ChartMuseum for Helm charts
chartmuseum:
  enabled: true

# Enable Notary for image signing
notary:
  enabled: true

# Garbage collection
gc:
  enabled: true
  schedule: "0 2 * * 6"  # Weekly on Saturday at 2am

# Metrics for monitoring
metrics:
  enabled: true
  serviceMonitor:
    enabled: false  # Enable if Prometheus operator is installed

# Resource limits
registry:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 2Gi
      cpu: 1000m

core:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1000m

jobservice:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1000m

database:
  type: internal
  internal:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 1Gi
        cpu: 500m

redis:
  type: internal
  internal:
    resources:
      requests:
        memory: 128Mi
        cpu: 50m
      limits:
        memory: 512Mi
        cpu: 250m
