# Auth API Gateway - Development Environment Values
# These values override the base Helm chart for dev environment

global:
  namespace: uo-dev
  imageRegistry: harbor.unifyops.io/library
  imagePullSecrets:
    - name: harbor-registry

stack:
  name: auth
  appType: api

enabled: true
replicaCount: 1

image:
  repository: auth-api
  tag: dev-latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8002
  targetPort: 8002

ingress:
  enabled: true
  className: nginx-private
  hosts:
    - host: dev.unifyops.io
      paths:
        - path: /api/auth
          pathType: Prefix
  tls:
    - secretName: dev-unifyops-tls
      hosts:
        - dev.unifyops.io

secrets:
  jwtSecret: "dev-jwt-secret-key"
  existingSecret: ""
  existingSecretJwtKey: "jwt-secret"

config:
  # Common config
  apiPort: "8002"
  environment: "development"
  logLevel: "DEBUG"

  # API Gateway config
  serviceUrl: "http://auth-service:8001"

  # Rate limiting
  rateLimitPerMinute: "60"
  corsAllowedOrigins: "*"

  # Auth verification endpoint (for other services)
  authApiUrl: "http://auth-api:8002"
  authApiPrefix: "/api/auth"

# Health checks
probes:
  readiness:
    enabled: true
    httpGet:
      path: "/api/auth/health"
      port: 8002
    initialDelaySeconds: 10
    periodSeconds: 10
  liveness:
    enabled: true
    httpGet:
      path: "/api/auth/health"
      port: 8002
    initialDelaySeconds: 30
    periodSeconds: 20

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi