apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: ">=1.7.0"
    helm:
      values: |
        persistence:
          enabled: true
          storageClassName: longhorn
          size: 40Gi
        tempo:
          storage:
            trace:
              backend: local
              wal:
                path: /var/tempo/wal
              local:
                path: /var/tempo/blocks

  syncPolicy:
    automated: { prune: true, selfHeal: true }
