apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: "1.86.5"
    helm:
      values: |
        oauthSecretVolume:
          enabled: true
          secretName: tailscale-oauth
          mountPath: /oauth

        extraEnv:
          - name: XDG_CONFIG_HOME
            value: /tmp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
