apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: tailscale
  source:
    repoURL: https://pkgs.tailscale.com/helmcharts
    chart: tailscale-operator
    targetRevision: "1.86.5"
    helm:
      values: |
        installCRDs: true
        oauth: {}
        operatorConfig:
          image:
            repository: tailscale/k8s-operator
            tag: v1.86.5
            pullPolicy: IfNotPresent
          defaultTags:
            - "tag:k8s-operator"
          logging: "info"
          extraEnv:
            - name: XDG_CONFIG_HOME
              value: /tmp
        ingressClass:
          enabled: true
          name: tailscale
        proxyConfig:
          image:
            repository: tailscale/tailscale
            tag: v1.86.5
          defaultTags: "tag:k8s"
          firewallMode: auto
        apiServerProxyConfig:
          allowImpersonation: "false"
          mode: "false"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
