apiVersion: v1
kind: Secret
metadata:
  name: kps-additional-scrape-configs
  namespace: observability
type: Opaque
stringData:
  additional-scrape-configs.yaml: |
    # Probing via blackbox
    - job_name: blackbox-http
      metrics_path: /probe
      params:
        module: [http_2xx]
      static_configs:
        - targets:
            - https://grafana.unifyops.io
            - https://harbor.unifyops.io
            - https://longhorn.unifyops.io
            - https://argocd.unifyops.io
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: prometheus-blackbox-exporter:9115

    # Non-K8s servers via node_exporter
    - job_name: node_exporter_static
      static_configs:
        - targets:
            - 192.168.50.84:9100   # UM790 Pro - adjust as needed
