apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: observability
spec:
  encryptedData:
    slack_api_url: REPLACE_WITH_YOUR_SEALED_VALUE
  template:
    metadata:
      name: alertmanager-slack-webhook
      namespace: observability
    type: Opaque
