apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: observability
  annotations:
    kubernetes.io/ingress.class: nginx-private
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  rules:
  - host: grafana.unifyops.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kps-grafana
            port:
              number: 80
  tls:
  - hosts: ["grafana.unifyops.io"]
    secretName: grafana-tls
