apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - grafana-ingress.yaml
  # - alertmanager-networkpolicy.yaml
  - additional-scrape-configs.secret.yaml
  # - alertmanager-slack-webhook.sealedsecret.yaml
  - servicemonitors/argocd.yaml
  - servicemonitors/cert-manager.yaml
  - servicemonitors/external-dns.yaml
  - servicemonitors/longhorn.yaml
  - servicemonitors/metrics-server.yaml
  - servicemonitors/traefik.yaml
