apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/KominskyOrg/unifyops-infra.git'
    - 'http://harbor-core.harbor-system.svc.cluster.local/chartrepo/library'
  destinations:
    - namespace: uo-*
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'