apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: arc
  namespace: argocd
spec:
  description: ARC (GitHub Actions Runner Controller) apps
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
