apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homelab
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/KominskyOrg/unifyops-infra.git'
  destinations:
    - namespace: homelab
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'