apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-operator
  template:
    metadata:
      labels:
        app: tailscale-operator
    spec:
      serviceAccountName: tailscale-operator
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: operator
          image: ghcr.io/tailscale/k8s-operator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: CLIENT_ID_FILE
              value: /secrets/client_id
            - name: CLIENT_SECRET_FILE
              value: /secrets/client_secret
            - name: TS_LOGS
              value: "true"
          resources:
            requests: { cpu: 100m, memory: 100Mi }
            limits:   { cpu: 500m, memory: 500Mi }
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet: { path: /readyz, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: oauth
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: oauth
          secret:
            secretName: tailscale-oauth
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
