apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - deployment.yaml
  - path-xdg.yaml
commonLabels:
  app.kubernetes.io/name: tailscale-operator
  app.kubernetes.io/part-of: tailscale
