apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  template:
    spec:
      containers:
      - name: operator
        env:
        - name: XDG_CONFIG_HOME
          value: /tmp
