apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale-operator
  namespace: tailscale
imagePullSecrets:
  - name: ghcr-creds   # created once: kubectl -n tailscale create secret docker-registry ghcr-creds ...
