apiVersion: v1
kind: Service
metadata:
  name: traefik-public
  namespace: kube-system
  labels: { app.kubernetes.io/name: traefik }
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector: { app.kubernetes.io/name: traefik }
  ports:
  - name: web
    port: 80
    targetPort: 8000
  - name: websecure
    port: 443
    targetPort: 8443
