apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # apply after controller is up
spec:
  project: infra
  source:
    repoURL: https://github.com/KominskyOrg/unifyops-infra.git
    targetRevision: HEAD
    path: clusters/unifyops-home/apps/metallb/config
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
