apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: infra
  source:
    repoURL: https://github.com/KominskyOrg/unifyops-infra.git
    targetRevision: HEAD
    path: clusters/unifyops-home/apps/metallb/config
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    retry:
      limit: 6
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
