apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifyops
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: app
          env:
            - name: ENV
              value: "dev"