apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: "1.16.0"
    helm:
      values: |
        externalURL: https://harbor.unifyops.io
        expose:
          type: ingress
          tls:
            enabled: true
            certSource: secret
            secret:
              secretName: harbor-tls
          ingress:
            className: nginx-private
            hosts:
              core: harbor.unifyops.io
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              external-dns.alpha.kubernetes.io/hostname: harbor.unifyops.io

        chartmuseum:
          enabled: true
        notary:
          enabled: false
        trivy:
          enabled: false

        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              storageClass: longhorn
              size: 100Gi
            database:
              storageClass: longhorn
              size: 10Gi
            redis:
              storageClass: longhorn
              size: 5Gi
            jobservice:
              storageClass: longhorn
              size: 10Gi
            trivy:
              storageClass: longhorn
              size: 10Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
