apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-auth
  namespace: docker-registry
type: Opaque
stringData:
  htpasswd: |
    admin:$2y$05$aBuOyqX5E5SAgJP53RwKOOKahc.OHvNwjShZQxkeykF1ZpBtjwMGC