apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: docker-registry

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - auth-secret.yaml

configMapGenerator:
  - name: docker-registry-config
    files:
      - config.yml